use_frameworks!

platform :ios, '10.0'

target 'MKLoRaWAN-SB_Example' do
  pod 'MKLoRaWAN-SB', :path => '../'

  target 'MKLoRaWAN-SB_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
